# Generated by Django 4.2.7 on 2025-11-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_nr', models.CharField(blank=True, max_length=10, verbose_name='PROMO/NR')),
                ('posto_graduacao', models.CharField(max_length=20, verbose_name='P/G')),
                ('nome_guerra', models.CharField(max_length=100, verbose_name='Nome de Guerra')),
                ('tipo_carreira', models.CharField(choices=[('CARREIRA', 'Carreira'), ('TEMPORÁRIO', 'Temporário')], max_length=20, verbose_name='Carreira')),
                ('secao', models.CharField(max_length=100, verbose_name='Seção')),
                ('substituto', models.CharField(blank=True, max_length=100, verbose_name='Substituto')),
                ('habilitacao', models.CharField(blank=True, max_length=10, verbose_name='Habilitação')),
                ('periodo_aquisitivo', models.CharField(max_length=4, verbose_name='Período Aquisitivo')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_termino', models.DateField(verbose_name='Data de Término')),
                ('data_apresentacao', models.DateField(verbose_name='Data de Apresentação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Férias',
                'verbose_name_plural': 'Férias',
                'db_table': 'ferias',
                'ordering': ['data_inicio'],
            },
        ),
    ]
